default: all
Q0 : Q0.c
	gcc -Wall -ansi -o binary/Q0 src/Q0.c
Q1 : Q1.c
	gcc -Wall -ansi -o binary/Q1 src/Q1.c
Q2 : Q2.c
	gcc -Wall -ansi -o binary/Q2 src/Q2.c
Q3 : Q3.c
	gcc -Wall -ansi -o binary/Q3 src/Q3.c
Q4 : Q4.c
	gcc -Wall -ansi -o binary/Q4 src/Q4.c
Q5 : Q5.c
	gcc -Wall -ansi -o binary/Q5 src/Q5.c
all:
	gcc -Wall -ansi -o binary/Q0 src/Q0.c
	gcc -Wall -ansi -o binary/Q1 src/Q1.c
	gcc -Wall -ansi -o binary/Q2 src/Q2.c
	gcc -Wall -ansi -o binary/Q3 src/Q3.c
	gcc -Wall -ansi -o binary/Q4 src/Q4.c
	gcc -Wall -ansi -o binary/Q5 src/Q5.c

clean:
	rm -f binary/Q*
