CC = python2
SOURCE = driver.py
INPUT = test test1 test2

stutest.out:
	$(CC) $(SOURCE) $(INPUT) > stutest.out
	@cat stutest.out

proftest.out:
	  $(CC) $(SOURCE) $(INPUT) > proftest.out
		@cat proftest.out

clean:
	@rm -f *.pyc *test.out
